//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Soap_Cons.WS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Book", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Book : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BookNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string YearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PublishField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Soap_Cons.WS.BookLocation bookLocationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string BookName {
            get {
                return this.BookNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BookNameField, value) != true)) {
                    this.BookNameField = value;
                    this.RaisePropertyChanged("BookName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Year {
            get {
                return this.YearField;
            }
            set {
                if ((object.ReferenceEquals(this.YearField, value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Publish {
            get {
                return this.PublishField;
            }
            set {
                if ((object.ReferenceEquals(this.PublishField, value) != true)) {
                    this.PublishField = value;
                    this.RaisePropertyChanged("Publish");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public Soap_Cons.WS.BookLocation bookLocation {
            get {
                return this.bookLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.bookLocationField, value) != true)) {
                    this.bookLocationField = value;
                    this.RaisePropertyChanged("bookLocation");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookLocation", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class BookLocation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationName1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationName2Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string LocationName1 {
            get {
                return this.LocationName1Field;
            }
            set {
                if ((object.ReferenceEquals(this.LocationName1Field, value) != true)) {
                    this.LocationName1Field = value;
                    this.RaisePropertyChanged("LocationName1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string LocationName2 {
            get {
                return this.LocationName2Field;
            }
            set {
                if ((object.ReferenceEquals(this.LocationName2Field, value) != true)) {
                    this.LocationName2Field = value;
                    this.RaisePropertyChanged("LocationName2");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS.WSSoap")]
    public interface WSSoap {
        
        // CODEGEN: Контракт генерации сообщений с именем FirstResult из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/First", ReplyAction="*")]
        Soap_Cons.WS.FirstResponse First(Soap_Cons.WS.FirstRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/First", ReplyAction="*")]
        System.Threading.Tasks.Task<Soap_Cons.WS.FirstResponse> FirstAsync(Soap_Cons.WS.FirstRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем SecondResult из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Second", ReplyAction="*")]
        Soap_Cons.WS.SecondResponse Second(Soap_Cons.WS.SecondRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Second", ReplyAction="*")]
        System.Threading.Tasks.Task<Soap_Cons.WS.SecondResponse> SecondAsync(Soap_Cons.WS.SecondRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FirstRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="First", Namespace="http://tempuri.org/", Order=0)]
        public Soap_Cons.WS.FirstRequestBody Body;
        
        public FirstRequest() {
        }
        
        public FirstRequest(Soap_Cons.WS.FirstRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FirstRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Id;
        
        public FirstRequestBody() {
        }
        
        public FirstRequestBody(int Id) {
            this.Id = Id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FirstResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FirstResponse", Namespace="http://tempuri.org/", Order=0)]
        public Soap_Cons.WS.FirstResponseBody Body;
        
        public FirstResponse() {
        }
        
        public FirstResponse(Soap_Cons.WS.FirstResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FirstResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Soap_Cons.WS.Book FirstResult;
        
        public FirstResponseBody() {
        }
        
        public FirstResponseBody(Soap_Cons.WS.Book FirstResult) {
            this.FirstResult = FirstResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SecondRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Second", Namespace="http://tempuri.org/", Order=0)]
        public Soap_Cons.WS.SecondRequestBody Body;
        
        public SecondRequest() {
        }
        
        public SecondRequest(Soap_Cons.WS.SecondRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SecondRequestBody {
        
        public SecondRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SecondResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SecondResponse", Namespace="http://tempuri.org/", Order=0)]
        public Soap_Cons.WS.SecondResponseBody Body;
        
        public SecondResponse() {
        }
        
        public SecondResponse(Soap_Cons.WS.SecondResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SecondResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Soap_Cons.WS.Book[] SecondResult;
        
        public SecondResponseBody() {
        }
        
        public SecondResponseBody(Soap_Cons.WS.Book[] SecondResult) {
            this.SecondResult = SecondResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSSoapChannel : Soap_Cons.WS.WSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSSoapClient : System.ServiceModel.ClientBase<Soap_Cons.WS.WSSoap>, Soap_Cons.WS.WSSoap {
        
        public WSSoapClient() {
        }
        
        public WSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Soap_Cons.WS.FirstResponse Soap_Cons.WS.WSSoap.First(Soap_Cons.WS.FirstRequest request) {
            return base.Channel.First(request);
        }
        
        public Soap_Cons.WS.Book First(int Id) {
            Soap_Cons.WS.FirstRequest inValue = new Soap_Cons.WS.FirstRequest();
            inValue.Body = new Soap_Cons.WS.FirstRequestBody();
            inValue.Body.Id = Id;
            Soap_Cons.WS.FirstResponse retVal = ((Soap_Cons.WS.WSSoap)(this)).First(inValue);
            return retVal.Body.FirstResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Soap_Cons.WS.FirstResponse> Soap_Cons.WS.WSSoap.FirstAsync(Soap_Cons.WS.FirstRequest request) {
            return base.Channel.FirstAsync(request);
        }
        
        public System.Threading.Tasks.Task<Soap_Cons.WS.FirstResponse> FirstAsync(int Id) {
            Soap_Cons.WS.FirstRequest inValue = new Soap_Cons.WS.FirstRequest();
            inValue.Body = new Soap_Cons.WS.FirstRequestBody();
            inValue.Body.Id = Id;
            return ((Soap_Cons.WS.WSSoap)(this)).FirstAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Soap_Cons.WS.SecondResponse Soap_Cons.WS.WSSoap.Second(Soap_Cons.WS.SecondRequest request) {
            return base.Channel.Second(request);
        }
        
        public Soap_Cons.WS.Book[] Second() {
            Soap_Cons.WS.SecondRequest inValue = new Soap_Cons.WS.SecondRequest();
            inValue.Body = new Soap_Cons.WS.SecondRequestBody();
            Soap_Cons.WS.SecondResponse retVal = ((Soap_Cons.WS.WSSoap)(this)).Second(inValue);
            return retVal.Body.SecondResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Soap_Cons.WS.SecondResponse> Soap_Cons.WS.WSSoap.SecondAsync(Soap_Cons.WS.SecondRequest request) {
            return base.Channel.SecondAsync(request);
        }
        
        public System.Threading.Tasks.Task<Soap_Cons.WS.SecondResponse> SecondAsync() {
            Soap_Cons.WS.SecondRequest inValue = new Soap_Cons.WS.SecondRequest();
            inValue.Body = new Soap_Cons.WS.SecondRequestBody();
            return ((Soap_Cons.WS.WSSoap)(this)).SecondAsync(inValue);
        }
    }
}
